### PR TITLE
Add EvaluateExprType to plugin interface

### PR DESCRIPTION
**Pull request by markliederbach**
This change adds a new client method called `EvaluateExprType`, which accepts the field `wantType` (`cty.Type`). This is passed to TFLint in `EvalExprRequest`. This will help to support plugins wanting to manually specify the type of an expression evaulation - such as in the case of reading tags from AWS Autoscaling Groups.

### CODE REVIEW

**Comment by wata727** [comment]
Hi @markliederbach, thank you for opening this PR.

Currently, this plugin system is experimental, so it's better to add an argument to `EvaluateExpr`than to add a new method. What do you think?

**Comment by wata727** [comment]
Ah... Sorry I misunderstand. In this case, it makes sense to add a new method. Please disregard my previous comment. 

Is this pull request ready for review?

**Comment by markliederbach** [comment]
Hi there - I have a couple more local changes I’ll need to finish up before it’s ready. I’ll update the PR once that’s done. Thanks for the feedback.

**Comment by markliederbach** [comment]
Yes, this is ready. I have the corresponding changes for tflint locally, but that shouldn’t block this part.

**Review by wata727 — APPROVED** [review]
Looks good. I'm going to merge this PR after reviewed the corresponding changes for TFLint.

**Comment by wata727** [comment]
Hi @markliederbach! Thank you for working on this.

I also need to support the `wantType` in the `EvaluateExpr` for the changes I was working on, so I merged it in https://github.com/terraform-linters/tflint-plugin-sdk/pull/83. Therefore, you will be able to specify the `wantType` from the next release without using this `EvaluateExprType`.

I will close this pull request. If you have any questions, feel free to reopen the PR. Thanks again!

**Pull request closed without merging**
