### PR TITLE
Fix heredoc parsing in parseConfig

### PR DESCRIPTION
**Pull request by syndicut**
Relates terraform-linters/tflint#1029

Workaround added in #93 should also be added to parseConfig function

### CODE REVIEW

**Comment by wata727** [comment]
This workaround works for expressions only. In the `parseConfig`, which handles the body, a newline is meaningful and cannot be added.

**Comment by syndicut** [comment]
> This workaround works for expressions only. In the `parseConfig`, which handles the body, a newline is meaningful and cannot be added.
Sad. So the only thing is to fix it in hcl library?

**Comment by wata727** [comment]
In my understanding, there is no problem in parsing the body (doesn't need the workaround). What problems are you facing?

**Comment by syndicut** [comment]
> In my understanding, there is no problem in parsing the body (doesn't need the workaround). What problems are you facing?

I'm trying to load Config() from plugin and have something like this in terraform configs:
```
resource "some_resource" "foo" {
  field         = <<EOF
contents
EOF
}
```
It causes error "Unterminated template string; No closing marker was found for the string."

**Comment by wata727** [comment]
Hmm, I can't reproduce the error with the above configuration. Could you share a minimal reproduction code?

**Comment by syndicut** [comment]
> Hmm, I can't reproduce the error with the above configuration. Could you share a minimal reproduction code?

1. Checkout code from this branch (I added Config loading rule to testing plugin for simplicity):
https://github.com/syndicut/tflint/tree/heredoc-bug
2. Build and install tflint itself
```
make install
```
3. Build and install plugin (for unknown reason I cannot reproduce this bug in e2e tests)
```
mkdir -p ~/.tflint.d/plugins
cd plugin/stub-generator/sources/testing
go build -o ~/.tflint.d/plugins/tflint-ruleset-testing
```
4. Go to heredoc sample in integration testing
```
cd integrationtest/inspection/heredoc/
```
5. Run tflint
```
tflint 
Failed to check ruleset. An error occurred:

Error: Failed to check `config_example` rule: template.tf:4,4-4: Unterminated template string; No closing marker was found for the string.

```

**Comment by syndicut** [comment]
Some workaround I found so far:
```
resource "aws_instance" "foo" {
  instance_type = <<EOF
t2.micro
EOF
  name = "test"
}
```
This will not cause any errors

**Comment by wata727** [comment]
Understood. Sure, this seems to be the same problem as https://github.com/hashicorp/hcl/issues/441. When transferring blocks, the inside of the brackets is sent to the plugins, so the newline is lost in the pattern where heredoc is declared in the end.

To avoid this, I think it is necessary to add a newline only when the end of the block contents is heredoc, but it seems a little difficult. It may be possible to implement a workaround, but it may require changes to the essential mechanics, such as https://github.com/terraform-linters/tflint-plugin-sdk/issues/89

**Comment by syndicut** [comment]
> Understood. Sure, this seems to be the same problem as [hashicorp/hcl#441](https://github.com/hashicorp/hcl/issues/441). When transferring blocks, the inside of the brackets is sent to the plugins, so the newline is lost in the pattern where heredoc is declared in the end.
> 
> To avoid this, I think it is necessary to add a newline only when the end of the block contents is heredoc, but it seems a little difficult. It may be possible to implement a workaround, but it may require changes to the essential mechanics, such as #89

Added some hackish and fragile way to guess if we need to add a newline based on diagnostics output

**Review by wata727 — APPROVED** [review]
😢

**Pull request merged**
